[visual]
# valid arguments: ["Bars", "Strings"]
visualisation = "Bars"

bottom_color= [0.0, 0.0, 0.0]
top_color = [1.0, 0.0, 0.0]
max_frequency = 15000
width = 1.0
smoothing_size = 5
smoothing_amount = 1
hide_cursor = false

# pressing F also toggles fullscreen
fullscreen = false
window_always_on_top = false

[processing]
buffering = 3
low_frequency_threshold = 50
low_frequency_scale_doubling = 5
low_frequency_smoothing_size = 5
low_frequency_smoothing = 1

# the further away from 1.0 the more fading, this could distort frequency threshold
low_frequency_fading = 2.5
low_frequency_volume_reduction = true

[audio]
pre_fft_windowing = true
volume_amplitude = 2.0
volume_factoring = 0.5
