[visual]
# valid arguments: ["Bars", "Strings"]
visualisation = "Strings"

bottom_color= [0.0, 0.0, 0.0]
top_color = [1.0, 0.0, 0.0]
max_frequency = 10000
width = 1.0
smoothing_size = 3
smoothing_amount = 1
hide_cursor = true

# pressing F also toggles fullscreen
fullscreen = false
window_always_on_top = false

[processing]
buffering = 2
low_frequency_threshold = 50
low_frequency_scale_doubling = 5
low_frequency_smoothing_size = 5
low_frequency_smoothing = 1

# the further away from 1.0 the more fading, this could distort frequency threshold
low_frequency_fading = 1.75
low_frequency_volume_reduction = true

[audio]
pre_fft_windowing = true
volume_amplitude = 0.25
volume_factoring = 1.0
