[visual]
bottom_color= [0.0, 0.0, 0.0]
top_color = [0.4, 0.0, 0.0]
bar_width = 1.0
buffering = 2
smoothing_size = 3
smoothing_amount = 1
max_frequency = 15000
low_frequency_threshold = 750
low_frequency_scale_doubling = 3
hide_cursor = false

[audio]
pre_fft_windowing = true
volume_amplitude = 0.5
